name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Compile
        run: pnpm run compile

      - name: Run tests
        run: pnpm pretest

      - name: Install VSIX
        run: pnpm setup && pnpm install -g @vscode/vsc

      - name: Package VSIX
        run: vsce package
