name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Compile
        run: pnpm run compile

      - name: Run tests
        run: pnpm pretest

      - name: Upgrade packages 🔀
        run: npm upgrade

      - name: Install VSIX
        run: npm install -g @vscode/vsce

      - name: Package VSIX
        run: vsce package

     # Prepare plugin archive content for creating artifact
      - name: Prepare Plugin Artifact
        id: artifact
        shell: bash
        run: |
          FILENAME=`ls *.vsix`
          echo "filename=${FILENAME" >> $GITHUB_OUTPUT

      # Store already-built plugin as an artifact for downloading
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: .
